os: linux
dist: trusty
sudo: required
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - sudo apt-get install libmicrohttpd-dev
  - sudo apt-get install llvm
  - sudo apt-get install qt58-meta-full
  - source /opt/qt58/bin/qt58-env.sh
  - qmake --version  
  - git clone --single-branch --recurse-submodules -j 2 --depth 1 https://github.com/grame-cncm/faust.git
  - make -C faust all
  - sudo make -C faust install
 
branches:
  only:
  - dev
  - master

script: make -C Build 
