os: linux
dist: bionic
sudo: required
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.0-xenial
  - sudo apt-get update -qq
  - sudo apt-get install libmicrohttpd-dev cmake qt511-meta-minimal libglu1-mesa-dev libsndfile1-dev libjack-jackd2-dev libasound2-dev -y
  - wget http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - tar xf clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
  - sudo rm -f   /usr/bin/llvm-config
  - sudo ln -s $(pwd)/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/llvm-config /usr/bin/llvm-config
  - source /opt/qt511/bin/qt511-env.sh
  - git clone --single-branch --recurse-submodules -j 2 --depth 1 https://github.com/grame-cncm/faust.git
  - make -C faust all
  - sudo make -C faust install
 
branches:
  only:
  - dev
  - master

script: make -C Build 
