os: linux
dist: xenial
sudo: required
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial
  - sudo apt-get update -qq
  - sudo apt-get install libmicrohttpd-dev
  - sudo apt-get install llvm
  - sudo apt-get install qt511base
  - source /opt/qt511/bin/qt511-env.sh
  - qmake --version 
  - llvm-config --version
  - git clone --single-branch --recurse-submodules -j 2 --depth 1 https://github.com/grame-cncm/faust.git
  - make -C faust all
  - sudo make -C faust install
 
branches:
  only:
  - dev
  - master

script: make -C Build 
