os: linux
dist: focal
sudo: required
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.2-focal
  - sudo apt-get update -qq
  - sudo apt-get install libmicrohttpd-dev cmake qt514-meta-minimal libglu1-mesa-dev libsndfile1-dev libjack-jackd2-dev libasound2-dev -y

#  - sudo rm -f  /usr/bin/llvm-config
#  - sudo ln -s  /usr/bin/llvm-config-10 /usr/bin/llvm-config
  - source /opt/qt514/bin/qt514-env.sh
#  - git clone --single-branch --recurse-submodules -j 2 --depth 1 https://github.com/grame-cncm/faust.git
#  - make -C faust all
#  - sudo make -C faust install

  - llvm-config --version
  - llvm-config-10 --version
  - which llvm-config
  - make -C faust/build cmake BACKENDS=all.cmake TARGETS=all.cmake CMAKEOPT="-DLLVM_CONFIG=llvm-config-10"
  - make -C faust/build
 
branches:
  only:
  - dev
  - master

script: 
  - make -C Build 
